# Generated by Django 4.2.5 on 2023-09-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadimage',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='user',
        ),
    ]
